# Generated by Django 5.2.7 on 2025-10-28 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alice_user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('telegram_user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressureMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('telegram_user_id', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Account Link Token',
                'verbose_name_plural': 'Account Link Tokens',
            },
        ),
    ]
