# Generated by Django 5.2.7 on 2025-10-31 09:05

from django.db import migrations, models
import django.db.models.deletion

def populate_user_fk(apps, schema_editor):
    BloodPressureMeasurement = apps.get_model('alice_skill', 'BloodPressureMeasurement')
    AliceUser = apps.get_model('alice_skill', 'AliceUser')
    first_user = AliceUser.objects.first()

    for measurement in BloodPressureMeasurement.objects.all():
        try:
            user = AliceUser.objects.get(alice_user_id=measurement.user_id)
            measurement.user_fk = user
            measurement.save()
        except AliceUser.DoesNotExist:
            if first_user:
                measurement.user_fk = first_user
                measurement.save()

class Migration(migrations.Migration):

    dependencies = [
        ('alice_skill', '0002_user_aliceuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpressuremeasurement',
            name='user_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='alice_skill.aliceuser'),
        ),
        migrations.RunPython(populate_user_fk),
        migrations.RemoveField(
            model_name='bloodpressuremeasurement',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='bloodpressuremeasurement',
            old_name='user_fk',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='bloodpressuremeasurement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='alice_skill.aliceuser'),
        ),
    ]
