# Generated by Django 5.2.7 on 2025-10-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice_skill', '0003_user_linktoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('telegram_user_id', models.BigIntegerField(db_index=True)),
                ('token_word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Account Link Token',
                'verbose_name_plural': 'Account Link Tokens',
            },
        ),
        migrations.AlterModelOptions(
            name='bloodpressuremeasurement',
            options={'ordering': ['-measured_at']},
        ),
        migrations.RenameField(
            model_name='bloodpressuremeasurement',
            old_name='created_at',
            new_name='measured_at',
        ),
        migrations.AlterField(
            model_name='bloodpressuremeasurement',
            name='diastolic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bloodpressuremeasurement',
            name='pulse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodpressuremeasurement',
            name='systolic',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='LinkToken',
        ),
    ]
