# Generated by Django 5.2.7 on 2025-11-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice_skill', '0003_replace_user_id_with_user_fk'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bloodpressuremeasurement',
            index=models.Index(fields=['user', '-measured_at'], name='bp_user_time_idx'),
        ),
    ]
