# Generated by Django 5.2.8 on 2025-11-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice_skill', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliceuser',
            name='telegram_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
