# Generated by Django 5.2.7 on 2025-10-24 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice_skill', '0004_accountlinktoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressuremeasurement',
            name='measured_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
