# Generated by Django 5.2.7 on 2025-10-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alice_skill', '0005_alter_bloodpressuremeasurement_measured_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
