# Generated by Django 5.2.7 on 2025-11-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('alice_skill', '0005_alter_telegram_user_id_to_hashed'),
    ]

    operations = [
        # AliceUser: rename, then ensure desired attributes
        migrations.RenameField(
            model_name='aliceuser',
            old_name='telegram_user_id',
            new_name='telegram_user_id_hash',
        ),
        migrations.AlterField(
            model_name='aliceuser',
            name='telegram_user_id_hash',
            field=models.CharField(
                max_length=64,
                null=True,
                blank=True,
                unique=True,
            ),
        ),
        # AccountLinkToken: rename, then adjust attributes
        migrations.RenameField(
            model_name='accountlinktoken',
            old_name='telegram_user_id',
            new_name='telegram_user_id_hash',
        ),
        migrations.AlterField(
            model_name='accountlinktoken',
            name='telegram_user_id_hash',
            field=models.CharField(
                max_length=64,
                db_index=True,
            ),
        ),
    ]
