# Generated by Django 5.2.7 on 2025-10-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alice_skill', '0006_user_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountlinktoken',
            name='token_word_count',
        ),
    ]
